import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import Header from "../../components/header";

const kannit = Kanit({
  subsets: ["latin", "latin-ext"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kannit.className} antialiased`}
        suppressHydrationWarning
      >
        <Header />

        <main className="flex-1 relative z-[1]">
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
